apiVersion: v1
kind: Service
metadata:
  name: face-recognizer-app
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      name: http
  selector:
    app: face-recognizer-app